# Generated by Django 5.2.1 on 2025-05-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentoEstrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('velocidade_media', models.FloatField()),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='monitorizacao.segmentoestrada')),
            ],
        ),
    ]
