# Generated by Django 5.2.1 on 2025-05-26 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('registado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistoPassagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorizacao.carro')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorizacao.segmentoestrada')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitorizacao.sensor')),
            ],
        ),
    ]
